export const CHANGE_NAME = 'HOME/CHANGE_NAME';
export const LOAD_REPOS = 'HOME/LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'HOME/LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'HOME/LOAD_REPOS_ERROR';
